### ISSUE TITLE
create auto import function for warehouses (if not exist)

### ISSUE THREAD

**Issue by patroklossam** [patroklossam/WareHouse#13]
Import from csv (list of names)

**Comment by srikanthnakka** [comment]
I would like work on this issue, Can you please share some more details about this issue

**Comment by patroklossam** [comment]
Hello!

if you check the application you will see that nearly everything is loaded from the DB. In the DB there is a table called Warehouse and at the moment has only 2 fields (id and name but more will be added in the future). So what you need to do is add a new item in the UI menu (maybe under File>Imports>"Warehouse from CSV") and

1.  load the csv file (at the moment should contain one name per line),
2.  parse it,
3.  get the last ID from the database (using hibernate)
4.  insert only the ones that do not exist already in the DB (using hibernate)

You can use any kind of library you want for the csv parsing, but please do it in a generic way so that people can extend it once more info is included for warehouses later.

**Comment by patroklossam** [comment]
Due to implementation on issue (import product from csv) please use the library commons csv from apache
