### ISSUE TITLE
Create class to handle all request to Hibernate and the database

### ISSUE THREAD

**Issue by patroklossam** [patroklossam/WareHouse#47]
Currently in every UI element you will find session of Hibernate and create statements etc etc.
Create a static class which will host method for all kind of queries needed from the application.

**Comment by MatteoPierro** [comment]
Hi @patroklossam if you want I can work on it. 
I have only one question. What do you think to have separated classes for each Entity to retrieve?
Something like `ProductDAO`, `CustomerDAO` .... etc.
Wdyt?

**Comment by patroklossam** [comment]
Hi @MatteoPierro,

Feel free to work on that! Currently I already have entities for every table in the db. 
(eg https://github.com/patroklossam/WareHouse/blob/master/src/main/java/com/storage/mywarehouse/Entity/Entry.java)

You don't mean that right? If not, yup create separate DAOs. You can create them as separate PRs if you want, to count as separate contributions for hacktoberfest!

**Comment by MatteoPierro** [comment]
Hi @patroklossam ,

four PRs are ready for this issue :)

The order is 

- https://github.com/patroklossam/WareHouse/pull/54
- https://github.com/patroklossam/WareHouse/pull/55
- https://github.com/patroklossam/WareHouse/pull/56
- https://github.com/patroklossam/WareHouse/pull/57

Let me know if you have any feedback.

**Comment by patroklossam** [comment]
Thanks again for your time and contribution! 
Enjoy Hacktoberfest!
