### ISSUE TITLE
create contributions.md

### ISSUE THREAD

**Issue by patroklossam** [patroklossam/WareHouse#51]

**Comment by Ikhiloya** [comment]
Hi, I's like to take this one. I'll need guidance though. Thanks

**Comment by patroklossam** [comment]
I put this as a really really easy PR. You just need to copy the Contributions part from the readme to a contributions.md, to match the guidelines of OSS that need a file like that!

**Comment by Ikhiloya** [comment]
okay, thanks, I'll begin work on it.
